# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Greg Emmen
# description:      ''
url:              ""
baseurl:          ""

author:
  name:           'Greg Emmen'

paginate:         5