# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Greg Emmen
tagline:          'Software & Controls Engineer'
description:      'Passionately '
url:              ""
baseurl:          ""

author:
  name:           'Greg Emmen'
  url:            https://twitter.com/GregulasMaximus

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/G-Emmen

header_pages:
  - portfolio.md
  - about.md