# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Greg Emmen
description:      'Software & Controls Engineer. 3D printing enthusiast. Boardgame developer. Working to make the world a better place'
url:              ""
baseurl:          ""

author:
  name:           'Greg Emmen'

paginate:         5

header_pages:
  - portfolio.md
  - about.md