title: Greg Emmen
author:
  name: Greg Emmen
  email: greg.emmen@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed



# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  social_links:
    - platform: github 
      user_url: "https://github.com/G-Emmen"
      title: GitHub profile
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/gregemmen/"
      title: LinkedIn profile

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - portfolio.md
  - about.md


# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false

